### ISSUE TITLE
Sort paths from CUDAapi.find_toolkit() in the descending order?

### ISSUE THREAD

**Issue by tkf** [JuliaGPU/CUDAapi.jl#95]
I had the same problem as #85:

```julia
julia> using CUDAapi

julia> CUDAapi.find_toolkit()
6-element Array{String,1}:
 "/usr/local/cuda-10.0/targets/x86_64-linux"
 "/usr/local/cuda-8.0"
 "/usr/local/cuda-9.0"
 "/usr/local/cuda-9.1"
 "/usr/local/cuda-10.0"
 "/usr/local/cuda-10.1"

julia> ENV["CUDA_HOME"] = "/usr/local/cuda-10.1"
"/usr/local/cuda-10.1"

julia> CUDAapi.find_toolkit()
1-element Array{String,1}:
 "/usr/local/cuda-10.1"

julia> using CUDAnative

julia> using CuArrays
```

Although I could workaround this by setting `CUDA_HOME`, it would be nice if `CUDAapi.find_toolkit` is a bit wise so that it returns the versions that are supported by `CUDAnative` first.

**Comment by maleadt** [comment]
Problem is that we really don't support multiple CUDA installations, i.e., we don't pick one from that list and use it, we search in all of them (this because some distro's like Debian like to spread CUDA all over the system so we _need_ to look in different directories).

I don't think it's useful to refactor this code to support such a use case right now; especially with a move to a BinaryBuilder-provided CUDA being worked on...

**Comment by tkf** [comment]
> with a move to a BinaryBuilder-provided CUDA being worked on...

This sounds great! Thanks for the explanation.
